variables:
  PROJECT_NAME: AtlasCreator
  BUILD_SETTINGS: buildsettings
  RELEASE_CONFIG: Release

  COMPILER: DEV

stages:
  - build
before_script:
  - $env:PROJECT_VERSION_MAJOR = GitVersion /showvariable Major
  - $env:PROJECT_VERSION_MINOR = GitVersion /showvariable Minor
  - $env:PROJECT_VERSION_PATCH = GitVersion /showvariable Patch
  - $env:PROJECT_VERSION_BUILD = GitVersion /showvariable BuildMetaData
  - if($env:PROJECT_VERSION_BUILD -eq ""){\
       $env:PROJECT_VERSION_BUILD=0\
   }
  - $env:PROJECT_VERSION = $env:PROJECT_VERSION_MAJOR + "." + $env:PROJECT_VERSION_MINOR + "." + $env:PROJECT_VERSION_PATCH
  - $env:PROJECT_VERSION_FULL = $env:PROJECT_VERSION_MAJOR + "." + $env:PROJECT_VERSION_MINOR + "." + $env:PROJECT_VERSION_PATCH + "." + $env:PROJECT_VERSION_BUILD
  - $env:PROJECT_FOLDER = Get-Location
build:
  stage: build
  except: 
        - tags
  tags: 
        - PowerGames
  script:
        - Get-Variable
        - Start-Process -Wait -FilePath "cmd.exe" -ArgumentList "/c .\build\build.cmd" -NoNewWindow
  artifacts:
        expire_in: 1 day
        paths: 
          - bin\*\*.exe 

